### ISSUE TITLE
VaspInteractive vs Vasp calculator

### ISSUE THREAD

**Issue by gauthierlab** [ulissigroup/finetuna#49]
Hello!

based on some of the previous issues, I think a problem I'm running into is related to the VaspInteractive calculator not being compatible with my custom build of vasp 5.4.4. So, I simply replaced `VaspInteractive' with `Vasp' from ase (~line 63 of the example wrapper script), and I get the following traceback:

Traceback (most recent call last):
  File ".../finetuna_wrapper.py", line 87, in <module>
    with vasp_calc as parent_calc:
AttributeError: __enter__

Is there something else I need to do that's being missed here?

**Comment by alchem0x2A** [comment]
@gauthierlab original `Vasp` does not have the context manager (the `with`-clause) so you just need to assign the `parent_calc` the normal way:

```
parent_calc = Vasp(**params)
```

and of course clean up the indentation etc in the code below. 

btw as the author of `VaspInteractive` there has been a new PR https://github.com/ulissigroup/vasp-interactive/pull/28 that enables some minimal support for vasp 5.4. You can try out the latest version (`>0.0.9`) of VaspInteractive if it solves your previous issue.

**Comment by gauthierlab** [comment]
Got it, thanks! The code now runs through the first relaxation with the ML potential, but fails after reaching the force cutoff and the subsequent VASP call:

`Traceback (most recent call last):
  File ".../finetuna_wrapper.py", line 109, in <module>
    relaxer.run(
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/finetuna/atomistic_methods.py", line 198, in run
    dyn.run(fmax=self.fmax, steps=self.steps)
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/optimize/optimize.py", line 294, in run
    return Dynamics.run(self)
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/optimize/optimize.py", line 181, in run
    for converged in Dynamics.irun(self):
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/optimize/optimize.py", line 168, in irun
    self.log()
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/optimize/optimize.py", line 308, in log
    forces = self.atoms.get_forces()
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/atoms.py", line 790, in get_forces
    forces = self._calc.get_forces(self)
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/calculators/abc.py", line 23, in get_forces
    return self.get_property('forces', atoms)
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/calculators/calculator.py", line 736, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/finetuna/online_learner/online_learner.py", line 189, in calculate
    energy, forces, fmax = self.get_energy_and_forces(atoms)
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/finetuna/online_learner/online_learner.py", line 259, in get_energy_and_forces
    energy, forces, constrained_forces = self.add_data_and_retrain(
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/finetuna/online_learner/online_learner.py", line 489, in add_data_and_retrain
    (new_data,) = convert_to_singlepoint([atoms])
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/finetuna/utils.py", line 31, in convert_to_singlepoint
    sample_energy = image.get_potential_energy(apply_constraint=False)
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/atoms.py", line 733, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/calculators/calculator.py", line 708, in get_potential_energy
    energy = self.get_property('energy', atoms)
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/calculators/calculator.py", line 736, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/calculators/vasp/vasp.py", line 331, in calculate
    self.read_results()
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/calculators/vasp/vasp.py", line 552, in read_results
    outcar = self.load_file('OUTCAR')
  File "/home/josegaut/.conda/envs/finetuna/lib/python3.9/site-packages/ase/calculators/vasp/vasp.py", line 655, in load_file
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'OUTCAR'`

It seems like it's trying to get the total energy and forces from OUTCAR, but of course it's not there because the calculation has not yet run. In case it's helpful, here is finetuna_wrapper.py: 

`from finetuna.atomistic_methods import Relaxation
from finetuna.online_learner.online_learner import OnlineLearner
from vasp_interactive import VaspInteractive
from ase.optimize import BFGS
from finetuna.ml_potentials.finetuner_ensemble_calc import FinetunerEnsembleCalc
from ase.io import Trajectory
from ase.calculators.vasp import Vasp
from finetuna.utils import calculate_surface_k_points

if __name__ == "__main__":

    traj = Trajectory(
        "./lastimage.traj"
    )  # change this path to your trajectory file

    ml_potential = FinetunerEnsembleCalc(
        checkpoint_paths=[
            "/home/josegaut/PythonModules/ocp/gemnet_t_direct_h512_all.pt",  # change this path to your gemnet checkpoint
        ],
        mlp_params=[
            {
                "tuner": {
                    "unfreeze_blocks": [
                        "out_blocks.3.seq_forces",
                        "out_blocks.3.scale_rbf_F",
                        "out_blocks.3.dense_rbf_F",
                        "out_blocks.3.out_forces",
                        "out_blocks.2.seq_forces",
                        "out_blocks.2.scale_rbf_F",
                        "out_blocks.2.dense_rbf_F",
                        "out_blocks.2.out_forces",
                        "out_blocks.1.seq_forces",
                        "out_blocks.1.scale_rbf_F",
                        "out_blocks.1.dense_rbf_F",
                        "out_blocks.1.out_forces",
                    ],
                    "num_threads": 8,
                },
                "optim": {
                    "batch_size": 1,
                    "num_workers": 0,
                    "max_epochs": 400,
                    "lr_initial": 0.0003,
                    "factor": 0.9,
                    "eval_every": 1,
                    "patience": 3,
                    "checkpoint_every": 100000,
                    "scheduler_loss": "train",
                    "weight_decay": 0,
                    "eps": 1e-8,
                    "optimizer_params": {
                        "weight_decay": 0,
                        "eps": 1e-8,
                    },
                },
                "task": {
                    "primary_metric": "loss",
                },
            },
        ],
    )

    parent_calc = Vasp(
    # vasp_calc = VaspInteractive(
        ibrion=-1,
        nsw=2000,
        isif=0,
        isym=0,
	ispin=2,
	ldipol=True,
	dipol=(0.5,0.5,0.5),
	idipol=3,
	sigma=0.5,
	ismear=0,
        ediffg=-0.03,
        encut=500.0,
        laechg=False,
        lcharg=False,
        lwave=False,
        ncore=16,
        gga="RP",
        pp="PBE",
        xc="PBE",
        kpts=(4,4,1),
    )

    learner = OnlineLearner(
	learner_params={
	    "stat_uncertain_tol": 1000000,
	    "dyn_uncertain_tol": 1000000,
	    "dyn_avg_steps": 15,
	    "query_every_n_steps": 100,
	    "num_initial_points": 0,
	    "initial_points_to_keep": [],
	    "fmax_verify_threshold": 0.03,
	    "tolerance_selection": "min",
	    "partial_fit": True,
	},
	parent_dataset=[],
	ml_potential=ml_potential,
	parent_calc=parent_calc,
	mongo_db=None,
	optional_config=None,
    )

    relaxer = Relaxation(
	initial_geometry=traj[0], optimizer=BFGS, fmax=0.03, steps=None, maxstep=0.2
    )
    relaxer.run(
	calc=learner,
	filename="online_learner_trajectory",
	replay_traj="parent_only",
	max_parent_calls=None,
	check_final=False,
	online_ml_fmax=learner.fmax_verify_threshold,
    )

    print("done!")`

**Comment by alchem0x2A** [comment]
yeah it seems a bit weird because after the vasp calculator hits `self.read_results()`, it means your VASP command returns without error, and yet still no OUTCAR file is generated. I guess this is less relevant to implementation of FINETUNA but something more local. Do you observe any output files? And are your able to run these calculations with just calling `$VASP_COMMAND` or `$ASE_VASP_COMMAND`?

And as a side note, when using original `Vasp` calculator `nsw=2000` should be `nsw=1` because these calculations are only single point DFT evaluations. (`VaspInteractive` keeps a long-running vasp process which requires larger NSW value to avoid early exit), but maybe not super relevant to your issue

@jmusiel Do you have any suggestions?

**Comment by gauthierlab** [comment]
Turns out this was a PEBKAC error. It works now -- thanks!

**Comment by alchem0x2A** [comment]
cool. I'm closing the issue now. meanwhile if you can take a test with latest vasp_interactive with vasp5.4 that would be great.
