### ISSUE TITLE
_message.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN6google8protobuf2io17SafeDoubleToFloatEd

### ISSUE THREAD

**Issue by yanzhangzh** [ulissigroup/finetuna#53]
When I was trying to finish the installation of Finetuna, I run the test from [N2H_Ag111_dissociation]. This was the error showing on my terminal.
/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/google/protobuf/internal/api_implementation.py:110: UserWarning: Selected implementation cpp is not available.
  warnings.warn(
Traceback (most recent call last):
  File "/hpcfs/users/a1732812/Test/11/N2H_Ag111.py", line 2, in <module>
    from finetuna.online_learner.online_learner import OnlineLearner
  File "/hpcfs/users/a1732812/xxx/finetuna/finetuna/online_learner/online_learner.py", line 5, in <module>
    from finetuna.logger import Logger
  File "/hpcfs/users/a1732812/xxx/finetuna/finetuna/logger.py", line 10, in <module>
    import wandb
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/wandb/sdk/__init__.py", line 5, in <module>
    from .wandb_artifacts import Artifact  # noqa: F401
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/wandb/sdk/wandb_artifacts.py", line 33, in <module>
    from wandb.apis import InternalApi, PublicApi
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/wandb/apis/__init__.py", line 42, in <module>
    from .internal import Api as InternalApi  # noqa
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/wandb/apis/internal.py", line 3, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 45, in <module>
    from ..lib import retry
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 17, in <module>
    from .mailbox import ContextCancelledError
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 10, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/wandb/proto/wandb_internal_pb2.py", line 8, in <module>
    from wandb.proto.v4.wandb_internal_pb2 import *
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/wandb/proto/v4/wandb_internal_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/google/protobuf/internal/builder.py", line 42, in <module>
    from google.protobuf import reflection as _reflection
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/google/protobuf/reflection.py", line 51, in <module>
    from google.protobuf import message_factory
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/google/protobuf/message_factory.py", line 45, in <module>
    from google.protobuf import descriptor_pool
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/google/protobuf/descriptor_pool.py", line 63, in <module>
    from google.protobuf import descriptor
  File "/hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 51, in <module>
    from google.protobuf.pyext import _message
ImportError: /hpcfs/users/a1732812/miniconda3/envs/finetuna/lib/python3.9/site-packages/google/protobuf/pyext/_message.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN6google8protobuf2io17SafeDoubleToFloatEd

So, could anyone tell me how can I be able to resolve the problem? Thank you so much!

**Comment by jmusiel** [comment]
It seems like this protocol buffer error is being caused in the wandb logging. You could try checking your wandb install and reinstalling it. Or try just disabling wandb in the example and see if it works.
